# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '3.1'

services:

  drupal_test:
    build: .
    container_name: drupal_test
    ports:
      - 8083:80  
    restart: always
    volumes:
        - ./sites:/var/www/html/sites
  db:
    image: mysql:5.7
    container_name: riaze_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: riaze143
    volumes:
        - ./mysql-data:/var/lib/mysql
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080